//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnvanterProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler
    {
        public int Id { get; set; }
        public string Kategori { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public string SeriNo { get; set; }
        public string Aciklama { get; set; }
        public string Kullanici { get; set; }
        public string Sube { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string Kaydeden { get; set; }
    }
}
