//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnvanterProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class YapilanCalismalar
    {
        public int Id { get; set; }
        public string BolgeMudurluk { get; set; }
        public string Sube { get; set; }
        public string YapilacakIs { get; set; }
        public string Durum { get; set; }
        public string IsıYapanPersonel { get; set; }
        public string Kaydeden { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    }
}
